/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidencialIndexRouteImport } from './routes/residencial.index'
import { Route as HotelesIndexRouteImport } from './routes/hoteles.index'
import { Route as ResidencialSlugRouteImport } from './routes/residencial.$slug'
import { Route as HotelesSlugRouteImport } from './routes/hoteles.$slug'

const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencialIndexRoute = ResidencialIndexRouteImport.update({
  id: '/residencial/',
  path: '/residencial/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelesIndexRoute = HotelesIndexRouteImport.update({
  id: '/hoteles/',
  path: '/hoteles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencialSlugRoute = ResidencialSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResidencialRoute,
} as any)
const HotelesSlugRoute = HotelesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HotelesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/hoteles/$slug': typeof HotelesSlugRoute
  '/residencial/$slug': typeof ResidencialSlugRoute
  '/hoteles/': typeof HotelesIndexRoute
  '/residencial/': typeof ResidencialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/hoteles/$slug': typeof HotelesSlugRoute
  '/residencial/$slug': typeof ResidencialSlugRoute
  '/hoteles': typeof HotelesIndexRoute
  '/residencial': typeof ResidencialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/hoteles/$slug': typeof HotelesSlugRoute
  '/residencial/$slug': typeof ResidencialSlugRoute
  '/hoteles/': typeof HotelesIndexRoute
  '/residencial/': typeof ResidencialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/hoteles/$slug'
    | '/residencial/$slug'
    | '/hoteles/'
    | '/residencial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/hoteles/$slug'
    | '/residencial/$slug'
    | '/hoteles'
    | '/residencial'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/hoteles/$slug'
    | '/residencial/$slug'
    | '/hoteles/'
    | '/residencial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  HotelesIndexRoute: typeof HotelesIndexRoute
  ResidencialIndexRoute: typeof ResidencialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residencial/': {
      id: '/residencial/'
      path: '/residencial'
      fullPath: '/residencial/'
      preLoaderRoute: typeof ResidencialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoteles/': {
      id: '/hoteles/'
      path: '/hoteles'
      fullPath: '/hoteles/'
      preLoaderRoute: typeof HotelesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residencial/$slug': {
      id: '/residencial/$slug'
      path: '/$slug'
      fullPath: '/residencial/$slug'
      preLoaderRoute: typeof ResidencialSlugRouteImport
      parentRoute: typeof ResidencialRoute
    }
    '/hoteles/$slug': {
      id: '/hoteles/$slug'
      path: '/$slug'
      fullPath: '/hoteles/$slug'
      preLoaderRoute: typeof HotelesSlugRouteImport
      parentRoute: typeof HotelesRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  HotelesIndexRoute: HotelesIndexRoute,
  ResidencialIndexRoute: ResidencialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
