/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResidencialRouteImport } from './routes/residencial'
import { Route as HotelesRouteImport } from './routes/hoteles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelesRouteImport } from './routes/hoteles.'

const ResidencialRoute = ResidencialRouteImport.update({
  id: '/residencial',
  path: '/residencial',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelesRoute = HotelesRouteImport.update({
  id: '/hoteles',
  path: '/hoteles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelesRoute = HotelesRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotelesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hoteles': typeof HotelesRouteWithChildren
  '/residencial': typeof ResidencialRoute
  '/hoteles/': typeof HotelesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/residencial': typeof ResidencialRoute
  '/hoteles': typeof HotelesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hoteles': typeof HotelesRouteWithChildren
  '/residencial': typeof ResidencialRoute
  '/hoteles/': typeof HotelesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hoteles' | '/residencial' | '/hoteles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/residencial' | '/hoteles'
  id: '__root__' | '/' | '/hoteles' | '/residencial' | '/hoteles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelesRoute: typeof HotelesRouteWithChildren
  ResidencialRoute: typeof ResidencialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/residencial': {
      id: '/residencial'
      path: '/residencial'
      fullPath: '/residencial'
      preLoaderRoute: typeof ResidencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoteles': {
      id: '/hoteles'
      path: '/hoteles'
      fullPath: '/hoteles'
      preLoaderRoute: typeof HotelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoteles/': {
      id: '/hoteles/'
      path: '/'
      fullPath: '/hoteles/'
      preLoaderRoute: typeof HotelesRouteImport
      parentRoute: typeof HotelesRoute
    }
  }
}

interface HotelesRouteChildren {
  HotelesRoute: typeof HotelesRoute
}

const HotelesRouteChildren: HotelesRouteChildren = {
  HotelesRoute: HotelesRoute,
}

const HotelesRouteWithChildren =
  HotelesRoute._addFileChildren(HotelesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelesRoute: HotelesRouteWithChildren,
  ResidencialRoute: ResidencialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
